class Levels(object):
    """description of class"""

    level_list = [{"Name":"1","map":[
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "X                       X",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
            ]},
            {"Name":"2","map":[
            "X                       X",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "X                       X"
            ]}]


