class Levels(object):
    """description of class"""

    level_list = [{"Name":"1","map":[
            "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "XSSSSSSSX        X      X",
            "XSSSSSSSX        X      X",
            "XXXSXXXXXXX   XXXXXX  XXX",
            "X                       X",
            "X   XXXXXXXFFFXXXXXX    X",
            "X   X     XFFFX    X    X",
            "X   XXXXXXXFFFXXXXXX    X",
            "X                       X",
            "X   XXXXXX   XXXXXXX    X",
            "X   X    X   X     X    X",
            "X   XXXXXX   XXXXXXX    X",
            "X                       X",
            "X   XXXXXXX    XXXXXX   X",
            "X   X     X    X    X   X",
            "X   XXXXXXX    XXXXXX   X",
            "X                       X",
            "X     XXXXX   XXXXXXX   X",
            "X     X   X   X     X   X",
            "X     XXXXX   XXXXXXX   X",
            "X                       X",
            "X                       X",
            "X XXXXX X XXX XXXXX X XXX",
            "X   X   X  X    X   X   X",
            "XXXXXXXXXXXXXXXXXXXXXXXXX"
            ]},
            {"Name":"2","map":[
            "X                       X",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "X                       X"
            ]}]


